### ISSUE TITLE
ee.Initialize(project='projectName')

### ISSUE THREAD

**Issue by georgeportoferreira** [sandroklippel/misc_noteboooks#1]
Olá Klippel!
A inicialização do cliente agora exige como argumento o nome do projeto.
Sugiro que a segunda células de código desses três NoteBooks passem a ser assim:
```
from google.colab import auth
auth.authenticate_user()

import ee
try:
  ee.Initialize(project='nomeDoProjeto')
except ee.ee_exception.EEException:
  ee.Authenticate()
  ee.Initialize(project='nomeDoProjeto')
```
Sugiro também colocar alguma orientação de como encontrar o nome do projeto no Code Editor. Um print como este abaixo acho que já ajuda. Um abraço!
![GEE](https://github.com/sandroklippel/misc_noteboooks/assets/3987484/9ad7cc73-d3ff-4bd9-93ef-892ef23f893d)

**Comment by sandroklippel** [comment]
Obrigado @georgeportoferreira! Fiz a atualização.
